package org.mitre.dtf.repository;

import static org.junit.Assert.*;

import java.util.HashSet;
import java.util.Set;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mitre.dtf.model.Card;
import org.mitre.dtf.model.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

/**
 * Unit testing of JpaCardRepository class. These tests makes some assumptions
 * about the initial state of the db as scripted in the cards.sql resource file.
 * 
 * @author wkim
 *
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("file:src/main/webapp/WEB-INF/application-context.xml")
public class JpaCardRepositoryTest {

	@Autowired
	JpaCardRepository cardRepository;

	/*
	 * See src/resources/db/*.sql files for expected initial data.
	 */
	
	@Test
	public void testInitialState() {

		Set<Card> cards = cardRepository.getAll();
		
		assertTrue(cards.size() == 2);
		
		Set<String> cardTitles = new HashSet<String>();
		
		for (Card c : cards) {
			cardTitles.add(c.getTitle());
		}
		
		assertTrue(cardTitles.contains("goldfish"));
		assertTrue(cardTitles.contains("fish flakes"));
	}
	
	@Test
	public void testRoundTrip() {
		
		Card testCard = new Card("aquarium", "holds fishies");
		
		cardRepository.save(testCard);
		Set<Card> cards = cardRepository.getAll();
		
		testCard.setId(3L); // card in db will have been autogenerated an id of 3
		testCard.setDependsTags(new HashSet<Tag>());
		testCard.setProvidesTags(new HashSet<Tag>());
		
		assertTrue(cards.size() == 3);
		assertTrue(cards.contains(testCard));
	}
	
	@Test
	public void testDepends() {
		
		Tag t = new Tag();
		t.setId(1L);
		t.setName("fishfood");
		
		Card c = cardRepository.getById(1); // should be the goldfish card with one depends tag
		Set<Tag> tags = c.getDependsTags();
		
		assertTrue(tags.size() == 1);
		assertTrue(tags.contains(t));
	}
	
	@Test
	public void testProvides() {
		
		Tag t = new Tag();
		t.setId(1L);
		t.setName("fishfood");
		
		Card c = cardRepository.getById(2); // should be the fish flakes card with one depends tag
		Set<Tag> tags = c.getProvidesTags();
		
		assertTrue(tags.size() == 1);
		assertTrue(tags.contains(t));
	}
	
}
